# Generated by Django 4.1 on 2022-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendsId', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=30)),
                ('eyeColor', models.TextField(max_length=30)),
                ('balance', models.TextField(max_length=100)),
                ('tags', models.JSONField()),
                ('greeting', models.TextField(max_length=200)),
                ('favoriteFruit', models.TextField(max_length=100)),
                ('friends', models.ManyToManyField(to='Persons.friend')),
            ],
        ),
    ]
