# Generated by Django 4.1 on 2022-08-09 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='personId',
            new_name='_id',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='persons',
            name='friends',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
